jobs:
  build:
    executor: python/default
    steps:
      - add_ssh_keys
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry build
          name: Build package
      - run:
          command: |
            poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
          name: Build package
orbs:
  codecov: codecov/codecov@1.1.3
  python: circleci/python@1.0.0
version: 2.1
workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
