name: Build Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    name: build docs on python 3.9

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - run: pip install poetry
      - name: Install dependencies
        run: poetry install

      - name: build-docs
        run: cd docs && poetry run python make_docs.py --output-file=pages

      - name: push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Auto updating pages.json"
          git push
